[wx]
appId = "wx190c5148b35ec8af"
appSecret = "ff4aae1e42471d863d335dc4bc5d958a"
templateId = "58cEgEMo30xWKivHUCQHjQIcgGmcE7ZFVpcWtqvZug0"
token = "CATER123123"

[user]
city = "长沙"
userIds = ["oAXn15v2cBLKKI_zhj2B8786uYJc"]
startData = "2022-07-09"
# 1农历
birthdayType = 1
birthday = "07-15"
# spec测试数据
#spec = "*/10 * * * * ?"
spec = "0 30 7 * * ?"

[redis]
host = "127.0.0.1:6379"
passwd = "dhyy"

